
server:
  port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/myproject?characterEncoding=utf8&useSSL=false&useAffectedRows=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    data:
      elasticsearch:
        cluster-nodes: 127.0.0.1:9300
        cluster-name: elasticsearch
        repositories:
          enabled: true
    rabbitmq:
      username: guest
      password: guest
      host: 127.0.0.1
      port: 5672
      publisher-confirms: true #  消息发送到交换机确认机制,是否确认回调
      listener:
        simple:
          acknowledge-mode: manual #消息消费手动确认
          concurrency: 1
          max-concurrency: 5
          retry:
            enabled: true
    redis:
      host: 127.0.0.1
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.myproject.domain,com.myproject.query


